/*********************************************************************\
	File name        : DialogIO.h
	Description      :
	Created at       : 16.08.01, @ 18:14:36
	Created by       : Thomas Kunert
	Modified by      :
\*********************************************************************/

#ifndef DIALOGIO_H__
#define DIALOGIO_H__

#include "res_textparser.h"

enum
{
	// types
	DRTYPE_UNKNOWN = 0,
	DRTYPE_COMBO_POPUP_CHILDREN,

	DRTYPE_OLDWIN,

	DRTYPE_DIALOG,
	DRTYPE_GROUP,
	DRTYPE_DLGGROUP,
	DRTYPE_RADIOGROUP,
	DRTYPE_WINDOWPIN,
	DRTYPE_SEPARATOR,
	DRTYPE_TAB,
	DRTYPE_SCROLLGROUP,

	DROLDWIN_POS_W,
	DROLDWIN_POS_H,
	DROLDWIN_POS_X,
	DROLDWIN_POS_Y,
	DROLDWIN_EDITTEXT,
	DROLDWIN_EDITNUMBER,
	DROLDWIN_EDITNUMBERARROWS,
	DROLDWIN_MULTILINETEXT,
	DROLDWIN_COMBOBOX,
	DROLDWIN_POPUPBUTTON,
	DROLDWIN_CHECKBOX,
	DROLDWIN_STATICTEXT,
	DROLDWIN_SLIDER,
	DROLDWIN_SLIDERNUM,
	DROLDWIN_GROUPBOX,
	DROLDWIN_BUTTON,
	DROLDWIN_OWNERDRAW,
	DROLDWIN_RADIOGADGET,
	DROLDWIN_SPECIALRADIO,
	DROLDWIN_LISTVIEW,
	DROLDWIN_ARROWBUTTON,
	DROLDWIN_COLORFIELD,
	DROLDWIN_SUBDIALOG,
	DROLDWIN_COMBOBUTTON,

	// flags

	//DR_TYPE,
	DR_ID,
	DR_NAME,
	DR_ALIGNMENT,
	DR_ARROWTYPE,
	DR_TAB_SELECTBY,

	DR_DLGGROUP_OK,
	DR_DLGGROUP_CANCEL,

	DR_COLUMNS,
	DR_ROWS,
	DR_EQUALROWS,
	DR_EQUALCOLS,
	DR_BORDERSTYLE,
	DR_ALLOW_WEIGHTS,

	DR_BORDERSIZE_L,
	DR_BORDERSIZE_R,
	DR_BORDERSIZE_T,
	DR_BORDERSIZE_B,

	DR_SPACE_X,
	DR_SPACE_Y,

	// scroll flags
	DR_SCROLL_V,
	DR_SCROLL_H,
	DR_SCROLL_BORDERIN,
	DR_SCROLL_STATUSBAR,
	DR_SCROLL_AUTO_H,
	DR_SCROLL_AUTO_V,
	DR_SCROLL_NOBLIT,
	DR_SCROLL_LEFT,

	DR_NUMCHILDREN,
	DR_CHILD,
	DR_CUSTOMGUI_OPEN,


	DRTYPE_DUMMY
};


class DialogParser : public ASCIIParser
{
public:
	virtual ~DialogParser() { }
};



#endif	// DIALOGIO_H__
