// C4D-DialogResource
DIALOG IDC_CMP_RES_ST_TABLE
{
  NAME IDS_DIALOG; CENTER_V; CENTER_H; 
  
  GROUP IDC_STATIC
  {
    NAME IDS_STATIC3; ALIGN_TOP; SCALE_H; 
    BORDERSIZE 0, 0, 0, 0; 
    COLUMNS 2;
    SPACE 4, 4;
    
    BUTTON IDC_BROWSE_RES_DIRECTORY { NAME IDS_BROWSE_BTN; ALIGN_TOP; ALIGN_LEFT; }
    STATICTEXT IDC_DIRECTORY_STATIC { NAME IDS_STATIC2; CENTER_V; SCALE_H; BORDERSTYLE BORDER_THIN_IN; }
  }
  STATICTEXT IDC_STATIC { NAME IDS_STATIC1; CENTER_V; ALIGN_LEFT; }
  TREEVIEW IDC_CUSTOM3
  {
    ALIGN_TOP; SCALE_H; SIZE 0, 100; 
    BORDER; 
    ALTERNATE_BG; 
    CURSORKEYS; 
  }
  CHECKBOX IDC_AVAILABLE_TABLE_CHK { NAME IDS_ONLY_MOD_ST_CHK; ALIGN_TOP; ALIGN_LEFT;  }
  STATICTEXT IDC_STATIC { NAME IDS_STATIC4; CENTER_V; ALIGN_LEFT; }
  TREEVIEW IDC_CUSTOM1
  {
    SCALE_V; SCALE_H; 
    BORDER; 
    ALTERNATE_BG; 
    CURSORKEYS; 
  }
  DLGGROUP { OK; CANCEL; }
}