// C4D-DialogResource
DIALOG IDC_STRING_TRANS_DIALOG
{
  NAME IDC_STRING_TRANS_DIALOG; SCALE_V; SCALE_H; 
  
  GROUP IDC_STATIC
  {
    ALIGN_TOP; SCALE_H; 
    BORDERSIZE 0, 0, 0, 0; 
    COLUMNS 3;
    SPACE 4, 4;
    
    STATICTEXT IDC_STATIC { NAME IDS_STRING_TRANS_CURRENT_DIR; CENTER_V; ALIGN_LEFT; }
    EDITTEXT IDC_ORIG_PATH_EDIT
    { CENTER_V; SCALE_H; SIZE 70, 0; }
    BUTTON IDC_ORIG_PATH_BTN { NAME IDS_BUTTON1; ALIGN_TOP; ALIGN_RIGHT; }
    STATICTEXT IDC_STATIC { NAME IDS_STRING_TRANS_NEW_STRING_DIR; CENTER_V; ALIGN_LEFT; }
    EDITTEXT IDC_NEW_PATH_EDIT
    { CENTER_V; SCALE_H; SIZE 70, 0; }
    BUTTON IDC_NEW_PATH_BTN { NAME IDS_BUTTON2; ALIGN_TOP; ALIGN_RIGHT; }
  }
  GROUP IDC_STATIC
  {
    ALIGN_TOP; SCALE_H; 
    BORDERSIZE 0, 0, 0, 0; 
    ROWS 1;
    SPACE 0, 0;
    
    STATICTEXT IDC_STATIC { NAME IDS_STRING_TRANS_AVAIL_ST; CENTER_V; ALIGN_LEFT; }
    STATICTEXT IDC_STATIC { NAME IDS_STATIC9; CENTER_V; SCALE_H; }
    STATICTEXT IDC_STATIC { NAME IDS_STATIC24; CENTER_V; ALIGN_LEFT; }
    POPUPBUTTON IDC_BASE_LANG_ARROW
    {
      CENTER_V; ALIGN_LEFT; 
      CHILDS
      {
      }
    }
    STATICTEXT IDC_STATIC { NAME IDS_STATIC25; CENTER_V; ALIGN_LEFT; SIZE 33, 0; }
    BUTTON IDC_ST_TRANS_SEARCH_BTN { NAME IDS_STRING_TRANS_SEARCH; ALIGN_TOP; ALIGN_LEFT; }
    BUTTON IDC_ST_TRANS_DEL_UNUSED_BTN { NAME IDS_STRING_TRANS_DEL_UNUSED; ALIGN_TOP; ALIGN_LEFT; }
    BUTTON IDC_ST_TRANS_COMPARE_BTN { NAME IDS_STRING_TRANS_COMPARE; CENTER_V; ALIGN_RIGHT; }
  }
  GROUP IDC_STATIC
  {
    NAME IDS_STATIC23; SCALE_V; SCALE_H; 
    BORDERSIZE 0, 0, 0, 0; 
    COLUMNS 1;
    ALLOW_WEIGHTS; 
    SPACE 4, 4;
    
    GROUP IDC_STATIC
    {
      NAME IDS_STATIC21; SCALE_V; SCALE_H; 
      BORDERSIZE 0, 0, 0, 0; 
      COLUMNS 1;
      SPACE 4, 4;
      
      TREEVIEW IDC_TABLES_TREE
      {
        SCALE_V; SCALE_H; SIZE 1000, 160; 
        BORDER; 
        HIDE_LINES; 
        NO_MULTISELECT; 
        HAS_HEADER; 
        RESIZE_HEADER; 
        MOVE_COLUMN; 
        FIXED_LAYOUT; 
        ALTERNATE_BG; 
        CURSORKEYS; 
      }
    }
    GROUP IDC_STATIC
    {
      NAME IDS_STATIC22; SCALE_V; SCALE_H; 
      BORDERSIZE 0, 0, 0, 0; 
      COLUMNS 1;
      SPACE 4, 4;
      
      GROUP IDC_STATIC
      {
        ALIGN_TOP; SCALE_H; 
        BORDERSIZE 0, 0, 0, 0; 
        COLUMNS 3;
        SPACE 4, 4;
        
        STATICTEXT IDC_STATIC { NAME IDS_STRING_TRANS_STRINGS; CENTER_V; SCALE_H; }
        GROUP IDC_STATIC
        {
          ALIGN_TOP; SCALE_H; 
          BORDERSIZE 0, 0, 0, 0; 
          COLUMNS 2;
          SPACE 4, 4;
          
          STATICTEXT IDC_STATIC { NAME IDS_STRING_TRANS_CHANGELANG; CENTER_V; ALIGN_LEFT; }
          POPUPBUTTON IDC_TRANSLATE_LANG_ARROW
          {
            ALIGN_TOP; ALIGN_LEFT; 
            CHILDS
            {
            }
          }
        }
        GROUP IDC_STATIC
        {
          NAME IDS_STATIC26; ALIGN_TOP; ALIGN_LEFT; 
          BORDERSTYLE BORDER_NONE; BORDERSIZE 0, 0, 0, 0; 
          COLUMNS 2;
          
          BUTTON IDC_TRANSLATE_LANG_GOTO_EMPTY_BTN { NAME IDS_TRANSLATE_LANG_GOTO_EMPTY; ALIGN_TOP; ALIGN_LEFT; }
          BUTTON IDC_TRANSLATE_LANG_GOTO_EMPTY_ALL_BTN { NAME IDS_TRANSLATE_LANG_GOTO_EMPTY_ALL; ALIGN_TOP; ALIGN_LEFT; }
          CHECKBOX IDC_TRANSLATE_LANG_SKIP_EMPTY_BASE_CHK { NAME IDS_TRANSLATE_LANG_SKIP_EMPTY_BASE; ALIGN_TOP; ALIGN_LEFT;  }
        }
      }
	  TREEVIEW IDC_STRINGS_TREE
      {
        SCALE_V; SCALE_H; 
        BORDER; 
        HIDE_LINES; 
        NO_MULTISELECT; 
        HAS_HEADER; 
        RESIZE_HEADER; 
        MOVE_COLUMN; 
        FIXED_LAYOUT; 
        ALTERNATE_BG; 
        CURSORKEYS; 
      }
      GROUP IDC_STATIC
      {
        ALIGN_TOP; SCALE_H; 
        BORDERSIZE 0, 0, 0, 0; 
        COLUMNS 2;
        SPACE 4, 4;
        
        STATICTEXT IDC_STATIC { NAME IDS_STRING_TRANS_US_NEW; CENTER_V; ALIGN_LEFT; }
        STATICTEXT IDC_ST_TRANS_US_NEW_STATIC { NAME IDS_ST_TRANS_US_NEW_STATIC; CENTER_V; SCALE_H; }
        STATICTEXT IDC_STATIC { NAME IDS_STRING_TRANS_COUNTRYSTRING; CENTER_V; ALIGN_LEFT; }
        EDITTEXT IDC_STRING_TRANS_COUNTRY_EDIT
        { CENTER_V; SCALE_H; SIZE 70, 0; }
        STATICTEXT IDC_STATIC { NAME IDS_STRING_TRANS_US_COMMAND; CENTER_V; ALIGN_LEFT; }
        STATICTEXT IDC_ST_TRANS_US_CMD_STATIC { NAME IDS_STATIC19; CENTER_V; SCALE_H; }
        STATICTEXT IDC_STATIC { NAME IDS_STRING_TRANS_COUNTRY_COMMAND; CENTER_V; ALIGN_LEFT; }
        EDITTEXT IDC_STRING_TRANS_COUNTRY_COMMAD_EDIT
        { CENTER_V; SCALE_H; SIZE 70, 0; }
      }
      GROUP IDC_STATIC
      {
        NAME IDS_STATIC20; ALIGN_TOP; CENTER_H; 
        BORDERSIZE 0, 0, 0, 0; 
        COLUMNS 2;
        SPACE 4, 4;
        
        BUTTON IDC_OK_BTN { NAME IDS_STRING_TRANS_CLOSE; ALIGN_TOP; CENTER_H; }
        BUTTON IDC_ST_TRANS_SAVE_TABLE_BTN { NAME IDS_STRING_TRANS_SAVE_TABLE; ALIGN_TOP; ALIGN_LEFT; }
      }
    }
  }
}