// C4D-DialogResource
DIALOG IDD_MAKE_DISTRI_DLG
{
  NAME IDS_DIALOG; SCALE_V; SCALE_H; 
  
  GROUP IDC_STATIC
  {
    NAME IDS_STATIC22; SCALE_V; SCALE_H; 
    BORDERSIZE 0, 0, 0, 0; 
    COLUMNS 1;
    ALLOW_WEIGHTS; 
    SPACE 4, 4;
    
    GROUP IDC_STATIC
    {
      NAME IDS_DISTRI_PRESETS; SCALE_V; SCALE_H; 
      BORDERSTYLE BORDER_GROUP_IN; BORDERSIZE 4, 4, 4, 4; 
      COLUMNS 1;
      SPACE 4, 4;
      
      TREEVIEW IDC_DISTR_PRESET_TREE
      {
        SCALE_V; SCALE_H; SIZE 0, 95; 
        BORDER; 
        HIDE_LINES; 
        HAS_HEADER; 
        FIXED_LAYOUT; 
        ALTERNATE_BG; 
      }
      GROUP IDC_STATIC
      {
        NAME IDS_STATIC6; ALIGN_TOP; ALIGN_LEFT; 
        BORDERSIZE 0, 0, 0, 0; 
        ROWS 1;
        SPACE 4, 4;
        
        BUTTON IDC_DISTR_NEW_PRESET_BTN { NAME IDS_DISTRI_PRESET_NEW; ALIGN_TOP; ALIGN_LEFT; }
        BUTTON IDC_DISTR_CLONE_BTN { NAME IDS_DISTRI_PRESET_CLONE_BTN; ALIGN_TOP; ALIGN_LEFT; }
        BUTTON IDC_DISTR_DELETE_PRESET_BTN { NAME IDS_DISTRI_PRESET_DEL_BTN; ALIGN_TOP; ALIGN_LEFT; }
        BUTTON IDC_DISTR_START_BTN { NAME IDS_DISTR_START; ALIGN_TOP; ALIGN_LEFT; }
        BUTTON IDC_DISTR_START_BATCH_BTN { NAME IDS_DISTRI_START_BATCH; ALIGN_TOP; ALIGN_LEFT; }
      }
      GROUP IDC_STATIC
      {
        NAME IDS_STATIC18; ALIGN_TOP; SCALE_H; 
        BORDERSIZE 0, 0, 0, 0; 
        COLUMNS 2;
        SPACE 4, 4;
        
        GROUP IDC_STATIC
        {
          NAME IDS_STATIC19; ALIGN_TOP; ALIGN_LEFT; 
          BORDERSIZE 0, 0, 20, 0; 
          COLUMNS 1;
          SPACE 4, 4;
          
          GROUP IDC_STATIC
          {
            ROWS 1;
            SPACE 4, 4;
            CHECKBOX IDC_DISTR_GENERATE_ZIP_CHK { NAME IDS_DISTR_GENERATE_ZIP; CENTER_V; ALIGN_LEFT;  }
            EDITNUMBERARROWS IDC_DISTR_GENERATE_ZIP_LEVEL { SIZE 20, 0; }
          }
          CHECKBOX IDC_DISTR_CHECK_VERSION_CHK { NAME IDS_CHECK_VERSION; ALIGN_TOP; ALIGN_LEFT;  }
          CHECKBOX IDC_DISTR_PARSE_SYMBOLS_CHK { NAME IDS_PARSE_SYMBOLS; ALIGN_TOP; ALIGN_LEFT;  }
        }
        GROUP IDC_STATIC
        {
          NAME IDS_STATIC20; ALIGN_TOP; SCALE_H; 
          BORDERSIZE 0, 0, 10, 0; 
          COLUMNS 2;
          SPACE 4, 4;
          
          STATICTEXT IDC_STATIC { NAME IDS_STATIC21; CENTER_V; ALIGN_LEFT; }
          EDITTEXT IDC_DISTR_PASSWORD_EDIT
          { CENTER_V; SCALE_H; SIZE 70, 0; }
          STATICTEXT IDC_STATIC { NAME IDS_STATIC23; CENTER_V; ALIGN_LEFT; }
          EDITTEXT IDC_DISTR_BUILDINFO_EDIT
          { CENTER_V; SCALE_H; SIZE 70, 0; }
        }
        CHECKBOX IDC_DISTR_CREATE_BUILDINFO_CHK { NAME IDS_DISTR_CREATE_BUILDINFO; ALIGN_TOP; ALIGN_LEFT;  }
        CHECKBOX IDC_DISTR_REMOVE_SCM_CHK { NAME IDS_DISTR_REMOVE_SCM; ALIGN_TOP; ALIGN_LEFT;  }
      }
      GROUP IDC_STATIC
      {
        NAME IDS_STATIC10; ALIGN_TOP; SCALE_H; 
        BORDERSIZE 0, 0, 0, 0; 
        COLUMNS 2;
        SPACE 4, 4;
        
        STATICTEXT IDC_STATIC { NAME IDS_DISTRI_ROOT_DIR; CENTER_V; ALIGN_LEFT; }
        FILENAME IDC_DISTR_ROOT_DIRECTORY
        {
          ALIGN_TOP; SCALE_H; 
          DIRECTORY; 
        }
        STATICTEXT IDC_STATIC { NAME IDS_STATIC11; CENTER_V; ALIGN_LEFT; }
        FILENAME IDC_DISTR_DESTINATION
        {
          ALIGN_TOP; SCALE_H; 
          SAVE; 
        }
      }
    }
    GROUP IDC_STATIC
    {
      NAME IDS_DISTRI_FILTER; SCALE_V; SCALE_H; 
      BORDERSTYLE BORDER_GROUP_IN; BORDERSIZE 4, 4, 4, 4; 
      COLUMNS 1;
      SPACE 4, 4;
      
      TREEVIEW IDC_DISTR_FILTER_TREE
      {
        SCALE_V; SCALE_H; 
        BORDER; 
        HIDE_LINES; 
        HAS_HEADER; 
        FIXED_LAYOUT; 
        ALTERNATE_BG; 
      }
      GROUP IDC_STATIC
      {
        NAME IDS_STATIC14; ALIGN_TOP; ALIGN_LEFT; 
        BORDERSIZE 0, 0, 0, 0; 
        ROWS 1;
        SPACE 4, 4;
        
        BUTTON IDC_DISTR_FILTER_NEW_BTN { NAME IDS_FILTER_NEW; ALIGN_TOP; ALIGN_LEFT; }
        BUTTON IDC_DISTR_FILTER_DEL_BTN { NAME IDS_FILTER_DELETE; ALIGN_TOP; ALIGN_LEFT; }
      }
      GROUP IDC_STATIC
      {
        NAME IDS_STATIC2; ALIGN_TOP; SCALE_H; 
        BORDERSIZE 0, 0, 0, 0; 
        COLUMNS 2;
        SPACE 4, 4;
        
        STATICTEXT IDC_STATIC { NAME IDS_DISTRI_FILTER_STRING; CENTER_V; ALIGN_LEFT; }
        EDITTEXT IDC_DISTR_FILTER_STRING
        { CENTER_V; SCALE_H; SIZE 70, 0; }
      }
      GROUP IDC_STATIC
      {
        NAME IDS_STATIC15; CENTER_V; SCALE_H; 
        BORDERSIZE 0, 0, 0, 0; 
        COLUMNS 3;
        SPACE 4, 4;
        
        STATICTEXT IDC_STATIC { NAME IDS_DISTRI_CONDITION; CENTER_V; ALIGN_LEFT; }
        COMBOBOX IDC_DISTR_FILTER_CONDITION_COMBO
        {
          CENTER_V; ALIGN_LEFT; SIZE 150, 0; 
          CHILDS
          {
            ID_DISTRI_COND_FILENAME_IS, IDS_DISTRI_COND_FILENAME_IS; 
            ID_DISTRI_COND_NAME_EXTENSION, IDS_DISTRI_COND_NAME_EXTENSION; 
            ID_DISTRI_COND_PATH_CONTAINS, IDS_DISTRI_COND_PATH_CONTAINS; 
            ID_DISTRI_COND_PATH_IS, IDS_DISTRI_COND_PATH_IS; 
            ID_DISTRI_COND_DIRECTORY_IS, IDS_DISTRI_COND_DIRECTORY_IS; 
          }
        }
        CHECKBOX IDC_DISTR_FILTER_FLAG_EXECUTABLE_CHK { NAME IDS_DISTR_FILTER_FLAG_EXECUTABLE; CENTER_V; ALIGN_RIGHT;  }
        STATICTEXT IDC_STATIC { NAME IDS_DISTRI_ACTION; CENTER_V; ALIGN_LEFT; }
        COMBOBOX IDC_DISTR_FILTER_ACTION_COMBO
        {
          CENTER_V; FIT_H; SIZE 150, 0; 
          CHILDS
          {
            ID_DISTRI_ACTION_INCLUDE, IDS_DISTRI_ACTION_INCLUDE; 
            ID_DISTRI_ACTION_EXCLUDE, IDS_DISTRI_ACTION_EXCLUDE; 
            ID_DISTRI_ACTION_RENAME, IDS_DISTRI_ACTION_RENAME; 
            ID_DISTRI_ACTION_MOVE_TO, IDS_DISTRI_ACTION_MOVE_TO; 
            ID_DISTRI_ACTION_COMPILE, IDS_DISTRI_ACTION_COMPILE; 
            ID_DISTRI_ACTION_COMPILE_KILL, IDS_DISTRI_ACTION_COMPILE_KILL; 
            ID_DISTRI_ACTION_FORCE_COPY, IDS_DISTRI_ACTION_FORCE_COPY; 
          }
        }
        EDITTEXT IDC_DISTR_FILTER_RENAME_EDIT
        { CENTER_V; SCALE_H; SIZE 70, 0; }
      }
    }
  }
  GROUP IDC_STATIC
  {
    NAME IDS_STATIC17; ALIGN_TOP; CENTER_H; 
    BORDERSIZE 0, 0, 0, 0; 
    COLUMNS 2;
    SPACE 4, 4;
    
    DLGGROUP { OK; }
    BUTTON IDC_DISTR_SAVE_PRESETS_BTN { NAME IDS_DISTRI_SAVE_BUTTONS; ALIGN_TOP; ALIGN_LEFT; }
  }
}