// C4D-DialogResource
DIALOG IDD_DISTRI_COMPR_DLG
{
  NAME IDS_DIALOG; FIT_V; SCALE_V; FIT_H; SCALE_H; 
  
  GROUP IDC_STATIC
  {
    NAME IDS_STATIC4; FIT_V; SCALE_V; FIT_H; SCALE_H; 
    BORDERSIZE 4, 4, 4, 4; 
    COLUMNS 1;
    SPACE 4, 4;
    
    STATICTEXT IDC_STATIC { NAME IDS_STATIC; CENTER_V; ALIGN_LEFT; }
    HYPERLINK IDC_DISTRI_COMPRESS_SRC_FILE
    {
      ALIGN_TOP; FIT_H; SCALE_H; 
      TEXT_ALIGN_LEFT;
    }
    STATICTEXT IDC_STATIC { NAME IDS_STATIC2; CENTER_V; ALIGN_LEFT; }
    HYPERLINK IDC_DISTRI_COMPRESS_DST_FILE
    {
      ALIGN_TOP; FIT_H; SCALE_H; 
      TEXT_ALIGN_LEFT;
    }
  }
  DLGGROUP { CANCEL; }
}