// C4D-DialogResource
DIALOG IDD_SEARCH_DIALOG
{
  NAME IDS_DIALOG; CENTER_V; CENTER_H;     GROUP IDC_STATIC
  {
    ALIGN_TOP; SCALE_H; 
    BORDERSIZE 0, 0, 0, 0; 
    ROWS 1;
    SPACE 4, 4;
    
    STATICTEXT IDC_STATIC { NAME IDS_SEARCH_STRING; CENTER_V; ALIGN_LEFT; }
    EDITTEXT IDC_SEARCH_EDIT
    { CENTER_V; SCALE_H; SIZE 70, 0; }
  }
  GROUP IDC_STATIC
  {    ALIGN_TOP; SCALE_H;     BORDERSIZE 0, 0, 0, 0; 
    ROWS 2;    SPACE 4, 4;
    
    GROUP IDC_STATIC
    {
      ALIGN_TOP; ALIGN_LEFT; 
      BORDERSIZE 0, 0, 0, 0; 
      COLUMNS 1;
      SPACE 4, 4;
      
      CHECKBOX IDC_SEARCH_REG_EXPR_CHK { NAME IDS_SEARCH_REGULAR_EXPRESSION; ALIGN_TOP; ALIGN_LEFT;  }
      CHECKBOX IDC_SEARCH_CASE_SENSITIVE_CHK { NAME IDS_SEARCH_CASE_SENSITIVE; ALIGN_TOP; ALIGN_LEFT;  }
    }
    GROUP IDC_STATIC
    {
      ALIGN_TOP; ALIGN_LEFT; 
      BORDERSIZE 0, 0, 0, 0; 
      ROWS 1;
      SPACE 4, 4;
      
      BUTTON IDC_SEARCH_FIND_NEXT_CURRENT_BTN { NAME IDS_SEARCH_FIND_NEXT; ALIGN_TOP; ALIGN_LEFT; }
      BUTTON IDC_SEARCH_FIND_NEXT_ALL_BTN { NAME IDS_SEARCH_FIND_NEXT_ALL; ALIGN_TOP; SCALE_H; }
      BUTTON IDC_SEARCH_CLOSE_BTN { NAME IDS_SEARCH_CLOSE; ALIGN_TOP; SCALE_H; }
    }
  }
}