// C4D-DialogResource
DIALOG IDD_DIFF_DISTRI_DLG
{
  NAME IDD_DIFF_DISTRI_DLG; SCALE_V; SCALE_H; 
  
  STATICTEXT IDC_STATIC { NAME IDS_STATIC; CENTER_V; ALIGN_LEFT; }
  TREEVIEW IDC_DIFF_DISTRI_FILES_TREE
  {
    SCALE_V; SCALE_H; 
    BORDER; 
    HIDE_LINES; 
    ALTERNATE_BG; 
    CURSORKEYS; 
  }
  GROUP IDC_STATIC
  {
    NAME IDS_STATIC3; ALIGN_TOP; ALIGN_LEFT; 
    BORDERSIZE 0, 0, 0, 0; 
    ROWS 1;
    EQUAL_COLS; 
    SPACE 4, 4;
    
    BUTTON IDC_DIFF_DISTRI_NEW_BTN { NAME IDS_BUTTON; ALIGN_TOP; SCALE_H; }
    BUTTON IDC_DIFF_DISTRI_REMOVE_BTN { NAME IDS_BUTTON1; ALIGN_TOP; SCALE_H; }
  }
  GROUP IDC_STATIC
  {
    NAME IDS_STATIC4; ALIGN_TOP; SCALE_H; 
    BORDERSIZE 0, 0, 0, 0; 
    COLUMNS 2;
    SPACE 4, 4;
    
    STATICTEXT IDC_STATIC { NAME IDS_STATIC1; CENTER_V; ALIGN_LEFT; }
    FILENAME IDC_DIFF_DISTRI_NEWZIP_EDIT
    {
      ALIGN_TOP; SCALE_H; 
    }
    STATICTEXT IDC_STATIC { NAME IDS_STATIC5; CENTER_V; ALIGN_LEFT; }
    FILENAME IDC_DIFF_DISTRI_DESTPATH_EDIT
    {
      ALIGN_TOP; SCALE_H; 
    }
    STATICTEXT IDC_STATIC { NAME IDS_STATIC6; CENTER_V; ALIGN_LEFT; }
    EDITTEXT IDC_DIFF_DISTRI_PASSWORD_EDIT
    { CENTER_V; SCALE_H; SIZE 70, 0; }
  }
  DLGGROUP { OK; CANCEL; }
}